## **Tensors**

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see Bridge with NumPy). Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autograd section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!

In [ ]:
import torch
import numpy as np

Directly from data

In [ ]:
data = [[1,2],[1,3]]
X_data = torch.tensor(data)

In [ ]:
X_data

tensor([[1, 2],
        [1, 3]])

From a NumPy array

In [ ]:
np_array = np.array(data)
X_np = torch.from_numpy(np_array)

In [ ]:
X_np

tensor([[1, 2],
        [1, 3]])

# Start

In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available using CPU")

GPU is available
using GPU : Tesla T4


Creating a Tensor

In [ ]:
#using empty
a =torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.2238, 0.2956, 0.7786],
        [0.3522, 0.9509, 0.3671]])

In [ ]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

#arrange
print("using arrange ->",torch.arange(0,10,2))

#using linespace
print("using linspace ",torch.linspace(0,10,10))

#using eye
print('using eye ', torch.eye(5))

#using full
print("using full ",torch.full((3,3),5))

using arrange -> tensor([0, 2, 4, 6, 8])
using linspace  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x = torch.tensor([[1,3,4],[4,5,6]])

In [ ]:
x

tensor([[1, 3, 4],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[134263436362416, 134263436362416, 134260008228912],
        [134264611264496,        10761296, 134260008228864]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype = torch.float64)


tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#using to ()
x.to(torch.float32)

tensor([[1., 3., 4.],
        [4., 5., 6.]])

# Mathematical

In [ ]:
x = torch.rand(2,2)

In [ ]:
x + 2
x-2
x*3
x/3
(x*100)//3


tensor([[23., 26.],
        [13., 30.]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

# inplace operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
m + n

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
m.add_(n)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
n

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])

In [ ]:
torch.relu(m)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

# copying a tensor

In [ ]:
a = torch.rand(2,3)

In [ ]:
b = a

In [ ]:
b

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [ ]:
b

tensor([[0.0000, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

# Tensor Operations On GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
#creating a new tensor on GPU
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a

tensor([[0.0000, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [ ]:
b = a.to(device)

In [ ]:
b + 5

tensor([[5.0000, 5.7003, 5.5277],
        [5.2472, 5.7909, 5.4235]], device='cuda:0')

# Reshaping Tensors

In [ ]:
a = torch.ones(4,4)

In [ ]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)

In [ ]:
b

tensor([[[0.0169, 0.2209, 0.9535, 0.7064],
         [0.1629, 0.8902, 0.5163, 0.0359],
         [0.6476, 0.3430, 0.3182, 0.5261]],

        [[0.0447, 0.5123, 0.9051, 0.5989],
         [0.4450, 0.7278, 0.4563, 0.3389],
         [0.6211, 0.5530, 0.6896, 0.3687]]])

In [ ]:
b.permute(2,0,1)

tensor([[[0.0169, 0.1629, 0.6476],
         [0.0447, 0.4450, 0.6211]],

        [[0.2209, 0.8902, 0.3430],
         [0.5123, 0.7278, 0.5530]],

        [[0.9535, 0.5163, 0.3182],
         [0.9051, 0.4563, 0.6896]],

        [[0.7064, 0.0359, 0.5261],
         [0.5989, 0.3389, 0.3687]]])

In [ ]:
c = torch.rand(226,226,3)

In [ ]:
d = torch.rand(1,20)

In [ ]:
c

tensor([[[0.9053, 0.8356, 0.3039],
         [0.6726, 0.5740, 0.9233],
         [0.9178, 0.7590, 0.7775],
         ...,
         [0.9128, 0.3356, 0.0426],
         [0.6426, 0.8048, 0.9173],
         [0.8631, 0.5196, 0.7514]],

        [[0.5117, 0.6630, 0.7960],
         [0.2162, 0.8056, 0.7325],
         [0.5663, 0.5072, 0.0658],
         ...,
         [0.8165, 0.4348, 0.6186],
         [0.7956, 0.1282, 0.4270],
         [0.2543, 0.6202, 0.1659]],

        [[0.7134, 0.0013, 0.4804],
         [0.3427, 0.3037, 0.9663],
         [0.9853, 0.9767, 0.9520],
         ...,
         [0.5582, 0.3579, 0.1122],
         [0.6152, 0.4207, 0.2460],
         [0.4301, 0.5817, 0.0254]],

        ...,

        [[0.0508, 0.2136, 0.2118],
         [0.5938, 0.8926, 0.4272],
         [0.2595, 0.1173, 0.2560],
         ...,
         [0.3238, 0.7355, 0.8038],
         [0.2213, 0.1583, 0.6835],
         [0.7315, 0.2190, 0.5256]],

        [[0.3657, 0.8577, 0.9057],
         [0.4218, 0.6984, 0.6048],
         [0.

In [ ]:
d

tensor([[0.6320, 0.5090, 0.3601, 0.2711, 0.8044, 0.6348, 0.9330, 0.6773, 0.5558,
         0.2637, 0.2796, 0.9473, 0.9075, 0.7746, 0.3436, 0.9904, 0.3872, 0.7749,
         0.7831, 0.8303]])